name: Terraform Frontend Apply

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'   # Solo se dispara si cambian archivos del frontend
  workflow_dispatch:    # Permite dispararlo manualmente

jobs:
  terraform:
    name: Terraform Apply Frontend
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      TF_WORKSPACE: frontend
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.2

      - name: Terraform Init
        working-directory: ./frontend
        run: terraform init -input=false

      - name: Terraform Validate
        working-directory: ./frontend
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./frontend
        run: terraform plan -out=tfplan -input=false

      - name: Terraform Apply
        working-directory: ./frontend
        run: terraform apply -input=false -auto-approve tfplan
