name: Deploy Frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Apply Frontend
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configurar AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Solo si usas rol temporal
          aws-region: us-east-1

      # 3. Configurar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.2

      # 4. Inicializar Terraform (si tu frontend est√° en una carpeta, agrega 'working-directory')
      - name: Terraform Init
        run: terraform init
        # working-directory: ./frontend

      # 5. Validar Terraform
      - name: Terraform Validate
        run: terraform validate
        # working-directory: ./frontend

      # 6. Aplicar Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve
        # working-directory: ./frontend
